name: Publish Release
on:
  release:
    types:
      - released
      - edited

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Publish
    environment: debug
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Az Login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Publish Release"
        uses: azure/cli@v2
        with:
          inlineScript: |
            filename=$RELEASE_NAME.tar.gz

            wget -O $filename $SRC_TARBALL_URI

            az storage blob upload \
              --file $filename \
              --account_name $STORAGE_ACCOUNT_NAME \
              --container bedrock \
              --name $RELEASE_NAME
        env:
          SRC_TARBALL_URI: ${{ github.event.release.tarball_url }}
          RELEASE_NAME: ${{ github.event.release.name }}
          STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
