name: Publish Release
on:
  workflow_call:
    inputs:
      release_name:
        description: "Release Name"
        required: true
        type: string
      source_tarball_url:
        description: "Release Name"
        required: true
        type: string

jobs:
  deployment:
    environment: debug
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: "Az Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Publish Release"
        uses: actions/github-script@v7
        with:
          script: |
            filename=$RELEASE_NAME.tar.gz

            wget -O $filename $SRC_TARBALL_URI

            az storage blob upload \
              --file $filename \
              --account_name $STORAGE_ACCOUNT_NAME \
              --container bedrock \
              --name $RELEASE_NAME
        env:
          SRC_TARBALL_URI: ${{ inputs.source_tarball_url }}
          RELEASE_NAME: ${{ inputs.release_name }}
          STORAGE_ACCOUNT_NAME: ${{ }}
