name: Publish Release
on:
  release:
    types:
      - released
      - edited

jobs:
  deployment:
    name: Publish
    environment: ${{ vars.ENV_NAME }}
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Az Login"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Add AgentIP to Storage Account Firewall
        run: |
          agentIP=$(curl -s https://api.ipify.org/)

          echo "agentIP: $agentIP"
          # save agentIP in env for remove task
          echo "agentIP=$agentIP" >> "$GITHUB_ENV" 

          az storage account network-rule add \
            --resource-group $STORAGE_ACCOUNT_RG \
            --account-name $STORAGE_ACCOUNT_NAME \
            --ip-address $agentIP \
            --output none
        env:
          STORAGE_ACCOUNT_RG: ${{ vars.STORAGE_ACCOUNT_RG }}
          STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}

      - name: "Publish Release"
        run: |
          filename=$RELEASE_NAME.tar.gz

          wget -O $filename $SRC_TARBALL_URI

          # give the firewall time to update
          sleep 30s

          az storage blob upload \
            --auth-mode login \
            --file $filename \
            --resource-group $STORAGE_ACCOUNT_RG \
            --account-name $STORAGE_ACCOUNT_NAME \
            --container $STORAGE_CONTAINER_NAME \
            --name $filename
        env:
          SRC_TARBALL_URI: ${{ github.event.release.tarball_url }}
          RELEASE_NAME: ${{ github.event.release.name }}
          STORAGE_ACCOUNT_RG: ${{ vars.STORAGE_ACCOUNT_RG }}
          STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
          STORAGE_CONTAINER_NAME: ${{ vars.STORAGE_CONTAINER_NAME }}

      - name: Remove AgentIP from Storage Account Firewall
        if: ${{ always() }}
        run: |
          agentIP=$(curl -s https://api.ipify.org/)

          az storage account network-rule remove \
            --resource-group $STORAGE_ACCOUNT_RG \
            --account-name $STORAGE_ACCOUNT_NAME \
            --ip-address $agentIP \
            --output none
        env:
          STORAGE_ACCOUNT_RG: ${{ vars.STORAGE_ACCOUNT_RG }}
          STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}

